 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: caption_coco_opt6.7b
  load_finetuned: True

  pretrained: "/gpfs01/huggingface/blip2/blip2_pretrained_opt6.7b.pth"
  finetuned: "/gpfs01/huggingface/blip2/blip2_caption_opt6.7b.pth"

  # vit encoder
  image_size: 364
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp32"
  freeze_vit: False

  # Q-Former
  num_query_token: 32

  # OPT
  opt_model: "/gpfs01/huggingface/opt-6.7b"

  # generation configs
  prompt: "a photo of"


preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 364
        eval:
          name: "blip_image_eval"
          image_size: 364
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
