Task:
  tag: 'llama3_infer_time'
  result_dir: './result/qa/rebuttal_exp'
  options: True
    # object_det: /mnt/cephfs/dataset/activitynet_captions/object_det
    # action_rec: /mnt/cephfs/dataset/activitynet_captions/action_cls
    # image_cap: /mnt/cephfs/dataset/activitynet_captions/caption
    # videochat: ./result/videochat_cap
    # clip_cap: /mnt/cephfs/dataset/activitynet_captions/clip_cap
    # video_cap
    # clip_caption_videochat
    # atomic_clipcap_videochat
Data:
  set_name: 'msrvtt_qa'
  data_paths:
    anet_qa:
      file: './data/qa/anet/val_qa_pair.json'
      video_dir: /path/to/anet_videos/ #/mnt/cephfs/dataset/activitynet_video/all_videos/
      clip_cap: './result/anet/clip_cap_visual_reduce_all/'
      text_emb: './m_result/anet/'
      video_cap: './result/anet/video_cap_visual_semantic_reduce_all/'
    msrvtt_qa:
      file: './data/qa/msrvtt/test_qa_re.json'
      video_dir: '/path/to/msrvtt/all_videos'
      clip_cap: './result/msrvtt/clip_cap_interpretable_all_visual_reduce'
      text_emb: './m_result/msrvtt/'
      video_cap: './result/msrvtt/video_cap_interpretable_all_visual_reduce'
    youcook:
      file: './data/youcook2/youcookii_annotations_trainval.json'
      video_dir: /path/to/youcook2/
    didemo:
      file: './data/DiDeMo/test_data_aval.json'
      video_dir: /path/to/didemo/test_videos
    ego_qa:
      file: './data/ego_schema/ego_schema.json'
      video_dir: /path/to/EgoSchema/good_clips_git/ #/mnt/cephfs/dataset/activitynet_video/all_videos/
      clip_cap: './result/ego/clip_cap/'
      text_emb: './m_result/ego/'
      video_cap: './result/ego/video_cap/'
    next_qa:
      file: './data/next_qa/val.json'
      video_dir: /path/to/NextVideo/videos
      clip_cap: './result/rebuttal_exp/next/clip_cap_base'
      text_emb: './m_result/next_qa/'
      video_cap: './result/rebuttal_exp/next/video_cap_base'
Model:
  models:  [llama2] # optional: ['sentence', 'angle','llama2']
  bs: 1
  SentenceEncoder:
    model_path: '/path/to/bert-base-nli-mean-tokens'
  Vicuna:
    clip_prompt: "A chat between a user who provides information about the content in a video and an assistant who can summarize the content of the video based on the information provided by the user."
    video_prompt: "A chat between a user who provides information about the content in a video and an assistant who can describe the content of the video in detail using 'first', 'then', 'after that',  and 'finnally' based on the information provided by the user. User: "
    model_path: '/path/to/vicuna-7b-v1.5-16k'
    max_new_tokens: 100
    temperature: 0.7
    repetition_penalty: 1.0
    min_length: 5
    length_penalty: 1.0
  Angle:
    pretrianed_weights: /chenyaofo/hf_models/Llama-2-13b-hf
    model_path: /path/to/angle-llama-13b-nli
  LlaMa2:
    model_path: /path/to/Llama-2-7b-chat-hf
  LlaMa3:
    model_path: /path/to/Meta-Llama-3.1-8B-Instruct/
Device: cuda
Infer:
  distributed: False
  verbose: ./result/
  topk: 5
